### ISSUE TITLE
learn to code

### ISSUE THREAD

**Issue by joker-119** [VirtualBrightPlayz/LabMod#1]
Protip: Don't call AppDomain.GetAssemblies() in OnUpdate..

**Comment by joker-119** [comment]
Also why are you defining System.Collections.IEnumerator, just declare IEnumerator, or just use MEC like everyone else

**Comment by FruitBoi** [comment]
+1

**Comment by VirtualBrightPlayz** [comment]
Thank you for telling me this, I am currently working on a fix.
