### ISSUE TITLE
What the fuck

### ISSUE THREAD

**Issue by FruitBoi** [VirtualBrightPlayz/LabMod#2]
Firstly, why are you calling AppDomain::GetAssemblies() in Update, you understand that this method is incredibly slow. Secondly, your code is a mess. Please use proper indentations.

**Comment by FruitBoi** [comment]
And why are you using the fully qualified name of System.Collections.IEnumerator instead of simply using "IEnumerator"

**Comment by joker-119** [comment]
+1 tabs are superior to spaces

**Comment by Kade-github** [comment]
@FruitBoi I took this kids code, added an api. Cleaned up code, and hey it actually works so much better, and you can make plugins for it so much easier. Holy shit is this guy bad at programming.
